### ISSUE TITLE
Python 3.8?

### ISSUE THREAD

**Issue by michaelaye** [seignovert/python-webgeocalc#8]
Hey!
Nice that you already wrote this!
I think we should either add this to planetarypy or at least make it a dependency, so that planetarypy users can get SPICE kernels easily. (That's my main interest for now).

But right now I can't even install it as it demands Python 3.6 (cough_dust... ;) ) so, let's update it!

I'll give it a go...

**Comment by michaelaye** [comment]
i see that GH head already supports 3.8, so all we need is a pip and conda package!

**Comment by seignovert** [comment]
You right. I just fixed a few minor bugs and pushed a new version to PyPI (`1.4.0`).
Now python `3.8` is the min requirement for this package.
